const Strings = {
	en: {
		// Dashboard Extra
		dashboardTitle: 'School Dashboard',
		greeting: 'Namaste, Mrs. Sharma',
		subtitle: 'Class Teacher: Grade 10-B',
		home: 'Home',
		messages: 'Messages',
		schedule: 'Schedule',
		account: 'Account',
		attendance: 'Mark Attendance',
		notice: 'Send Notice',
		homework: 'Add Homework',
		marks: 'Upload Marks',
		todaySchedule: 'Today’s Schedule',
		pendingTasks: 'Pending Tasks',
		urgent: 'URGENT',
		viewAll: 'View All',
		homeworkPosted: 'Homework Posted Successfully',
		homeworkPostedDesc: 'The assignment has been distributed to all students in the selected class.',
		assignmentSummary: 'Assignment Summary',
		backToDashboard: 'Back to Dashboard',
		viewHomework: 'View Homework',
		subjectLabel: 'Subject',
		classLabel: 'Class',
		dueDateLabel: 'Due Date',
		reminderHomeworkTitle: 'TEACHER PORTAL',
		activeSession: 'Active Session',
		sendingReminderFor: 'Sending reminder for ',
		targetingStudents: 'Targeting students with missing assignments: ',
		pendingSubmissions: 'Pending Submissions',
		selectAll: 'Select All',
		showMoreStudents: 'Show {count} more students',
		reminderMessageLabel: 'Reminder Message (Optional)',
		reminderMessageHelper: 'Students will receive this as a push notification and email.',
		sendReminder: 'Send Reminder',
		defaultReminderMsg: 'Please submit your quadratic equations assignment by tomorrow.',
		editHomeworkTitle: 'Edit Homework',
		editHomeworkSubtitle: 'Update the assignment details for your Mathematics class.',
		selectClass: 'Select Class',
		selectSubject: 'Select Subject',
		homeworkDetails: 'Homework Details',
		attachments: 'Attachments',
		addMoreAttachments: 'Add More Attachments',
		saveChanges: 'Save Changes',
		cancel: 'Cancel',
		schoolNotices: 'School Notices',
		searchNotices: 'Search notices...',
		allClasses: 'All Classes',
		grade10A: 'Grade 10-A',
		grade10B: 'Grade 10-B',
		important: 'Important',
		sent: 'Sent',
		uploadMarksTitle: 'Upload Marks',
		uploadMarksDesc: 'Update student performance for the current term.',
		studentsList: 'Students List',
		totalMarks: 'Total: /100',
		verifyMarksNote: 'Verify marks before uploading. Changes after submission require coordinator approval.',
		saveAndUpload: 'Save & Upload Marks',
		rollNo: 'Roll No',
		marksUploadedSuccess: 'Marks Uploaded Successfully',
		marksUploadedDesc: 'The marks for Grade 10-B (Mathematics) have been processed and archived.',
		recordSummary: 'Record Summary',
		verifiedAndSaved: 'Verified & Saved',
		viewMarksheet: 'View Marksheet',
		filename: 'Grade_10B_Math_Final.pdf',
		fileMeta: 'Signed Copy • 2.4 MB',
		studentsCount: '32',
		studentMarksheet: 'Student Marksheet',
		averageScore: 'Average Score',
		searchRecords: 'Search Records',
		searchPlaceholder: 'Search by student name or roll no',
		downloadPDFMarksheet: 'Download PDF Marksheet',
		pass: 'Pass',
		pending: 'Pending',
		roll: 'ROLL',
		studentName: 'STUDENT NAME',
		marksHeader: 'MARKS',
		statusHeader: 'STATUS',


	},
hi:{
	
}
};

export default Strings;
