const Strings = {
	en: {
		// Dashboard Extra
		dashboardTitle: 'School Dashboard',
		greeting: 'Namaste, Mrs. Sharma',
		subtitle: 'Class Teacher: Grade 10-B',
		home: 'Home',
		messages: 'Messages',
		schedule: 'Schedule',
		account: 'Account',
		attendance: 'Mark Attendance',
		notice: 'Send Notice',
		homework: 'Add Homework',
		marks: 'Upload Marks',
		todaySchedule: 'Today’s Schedule',
		pendingTasks: 'Pending Tasks',
		urgent: 'URGENT',
		viewAll: 'View All',
		homeworkPosted: 'Homework Posted Successfully',
		homeworkPostedDesc: 'The assignment has been distributed to all students in the selected class.',
		assignmentSummary: 'Assignment Summary',
		backToDashboard: 'Back to Dashboard',
		viewHomework: 'View Homework',
		subjectLabel: 'Subject',
		classLabel: 'Class',
		dueDateLabel: 'Due Date',
		reminderHomeworkTitle: 'TEACHER PORTAL',
		activeSession: 'Active Session',
		sendingReminderFor: 'Sending reminder for ',
		targetingStudents: 'Targeting students with missing assignments: ',
		pendingSubmissions: 'Pending Submissions',
		selectAll: 'Select All',
		showMoreStudents: 'Show {count} more students',
		reminderMessageLabel: 'Reminder Message (Optional)',
		reminderMessageHelper: 'Students will receive this as a push notification and email.',
		sendReminder: 'Send Reminder',
		defaultReminderMsg: 'Please submit your quadratic equations assignment by tomorrow.',
		editHomeworkTitle: 'Edit Homework',
		editHomeworkSubtitle: 'Update the assignment details for your Mathematics class.',
		selectClass: 'Select Class',
		selectSubject: 'Select Subject',
		homeworkDetails: 'Homework Details',
		attachments: 'Attachments',
		addMoreAttachments: 'Add More Attachments',
		saveChanges: 'Save Changes',
		cancel: 'Cancel',
		schoolNotices: 'School Notices',
		searchNotices: 'Search notices...',
		allClasses: 'All Classes',
		grade10A: 'Grade 10-A',
		grade10B: 'Grade 10-B',
		important: 'Important',
		sent: 'Sent',
		uploadMarksTitle: 'Upload Marks',
		uploadMarksDesc: 'Update student performance for the current term.',
		studentsList: 'Students List',
		totalMarks: 'Total: /100',
		verifyMarksNote: 'Verify marks before uploading. Changes after submission require coordinator approval.',
		saveAndUpload: 'Save & Upload Marks',
		rollNo: 'Roll No',
		marksUploadedSuccess: 'Marks Uploaded Successfully',
		marksUploadedDesc: 'The marks for Grade 10-B (Mathematics) have been processed and archived.',
		recordSummary: 'Record Summary',
		verifiedAndSaved: 'Verified & Saved',
		viewMarksheet: 'View Marksheet',
		filename: 'Grade_10B_Math_Final.pdf',
		fileMeta: 'Signed Copy • 2.4 MB',
		studentsCount: '32',
		studentMarksheet: 'Student Marksheet',
		averageScore: 'Average Score',
		searchRecords: 'Search Records',
		searchPlaceholder: 'Search by student name or roll no',
		downloadPDFMarksheet: 'Download PDF Marksheet',
		pass: 'Pass',
		pending: 'Pending',
		roll: 'ROLL',
		studentName: 'STUDENT NAME',
		marksHeader: 'MARKS',
				statusHeader: 'STATUS',
		// Welcome Screen
		schoolConnect: 'SCHOOL CONNECT',
		welcomeTitle: 'Welcome to Digital School Diary',
		welcomeSubtitle: 'Your central hub for academic excellence and secure school-to-home communication.',
		feature1Title: 'Track Student Progress',
		feature1Desc: 'View real-time updates on grades, attendance, and achievements.',
		feature2Title: 'Receive School Notices Instantly',
		feature2Desc: 'Stay informed about closures, events, and important announcements.',
		feature3Title: 'Stay Connected with Teachers',
		feature3Desc: 'Direct channel for communication with your child\'s educators.',
		getStarted: 'Get Started',
		alreadyAccount: 'Already have an account? Log in',
		govService: 'GOVERNMENT SERVICE',
		officialService: 'Official Education Department Service © 2024',
		privacyPolicy: 'Privacy Policy',
		support: 'Support',
		terms: 'Terms',
		// Student Registration
		studentRegistration: 'Student Registration',
		step1of2: 'Step 1 of 2',
		fiftyPercentComplete: '50% Complete',
		createStudentProfile: 'Create Student Profile',
		registrationSubtitle: "Please provide the student's official details as registered in the school records.",
		studentFullName: 'Student Full Name',
		fullNamePlaceholder: 'Enter full name',
		studentID: 'Student ID',
		studentIDPlaceholder: 'e.g. 1002345',
		schoolName: 'School Name',
		selectSchool: 'Select your school',
		officialRegistration: 'Official Registration',
		encryptionNote: 'Your information is secured using government-grade encryption.',
		registerContinue: 'Register & Continue',
		helpFindingID: 'Need help finding your Student ID?',
		contactSchool: ' Contact your school office.',
		// School Names
		school1: 'Central District High School',
		school2: 'North Star Elementary Academy',
		school3: 'Riverdale Primary School',
		school4: 'West View Technical Institute',
		// Welcome Back (Login)
		eduPortal: 'EduPortal',
		dsds: 'DSDS',
		welcomeBack: 'Welcome Back',
		welcomeBackSubtitle: "Access your child's progress or manage your classroom",
		chooseRole: 'Choose your role:',
		parent: 'Parent',
		teacher: 'Teacher',
		mobileNumber: 'Mobile Number',
		mobilePlaceholder: 'Enter 10-digit mobile number',
		countryCode: '+91',
		otpNote: 'We will send a 6-digit code to this number.',
		sendOTP: 'Send OTP',
		dataSafeNote: 'Your data is safe. Managed by the National Education Authority.',
		helpLoggingIn: 'Need help logging in?',
		languageEnglish: 'Language: English',
		privacy: 'Privacy',
		// OTP Verification
		identityVerification: 'Identity Verification',
		verifyYourNumber: 'Verify Your Number',
		otpSubtitle: 'Enter the 6-digit code sent to your mobile',
		verifyProceed: 'Verify & Proceed',
		didntReceive: "Didn't receive the code?",
		resendCode: 'Resend Code',
		secureInstitutional: 'Secure Institutional Verification',
		needHelp: 'Need Help?',
		helpDesc: 'If you are unable to verify your number, please visit the school administrative office.',
		adminSupport: 'Administrative Support',
		availableHours: 'Available Mon-Fri, 8AM - 4PM',
		// Parent Registration
		parentRegistration: 'Parent Registration',
		step2of2: 'Step 2 of 2',
		hundredPercentComplete: '100% Complete',
		parentGuardianInfo: 'Parent/Guardian Information',
		parentRegistrationSubtitle: 'Please provide your contact details to complete the registration.',
		parentFullName: 'Parent/Guardian Full Name',
		parentFullNamePlaceholder: 'Enter your full name',
		relationshipToStudent: 'Relationship to Student',
		selectRelationship: 'Select relationship',
		dataProtection: 'Data Protection',
		dataProtectionNote: 'Your contact information is stored securely on government servers.',
		completeRegistration: 'Complete Registration',
		father: 'Father',
		mother: 'Mother',
		guardian: 'Guardian',
		other: 'Other',
		// Offline Mode
		offlineTitle: "You're Offline",
		offlineDesc: "Your changes are saved locally and will sync once you're back online. You can continue managing student records without interruption.",
		savedOffline: 'Saved Offline',
		docsPending: '4 documents pending sync',
		ready: 'Ready',
		syncStatus: 'Sync Status',
		dataSafe: 'All data safe on this device.',
		continueWork: 'Continue Work',
		checkConnection: 'Check Connection',
		sync: 'Sync',
		homeTab: 'Home',
		studentsTab: 'Students',
		docsTab: 'Documents',
	},
	hi: {
		schoolConnect: 'स्कूल कनेक्ट',
		welcomeTitle: 'डिजिटल स्कूल डायरी में आपका स्वागत है',
		welcomeSubtitle: 'शैक्षणिक उत्कृष्टता और सुरक्षित स्कूल-टू-घर संचार के लिए आपका केंद्रीय केंद्र।',
		feature1Title: 'छात्र प्रगति को ट्रैक करें',
		feature1Desc: 'ग्रेड, उपस्थिति और उपलब्धियों पर रीयल-टाइम अपडेट देखें।',
		feature2Title: 'स्कूल नोटिस तुरंत प्राप्त करें',
		feature2Desc: 'बंद होने, घटनाओं और महत्वपूर्ण घोषणाओं के बारे में सूचित रहें।',
		feature3Title: 'शिक्षकों के साथ जुड़े रहें',
		feature3Desc: 'आपके बच्चे के शिक्षकों के साथ संचार के लिए सीधा चैनल।',
		getStarted: 'शुरू करें',
		alreadyAccount: 'पहले से ही एक खाता है? लॉग इन करें',
		govService: 'सरकारी सेवा',
		officialService: 'आधिकारिक शिक्षा विभाग सेवा © 2024',
		privacyPolicy: 'गोपनीयता नीति',
		support: 'सहायता',
		terms: 'शर्तें',
	}
};

export default Strings;
